name: directories
description: >
  A library to locate common directories using platform-specific conventions.
version: 0.1.0
repository: https://github.com/devoncarew/directories

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
